/*
 * Copyright (c) 2021 Infineon Technologies AG. All Rights Reserved.
 *
 * Use of this file is subject to the terms of use of the Evaluation Software License Agreement
 * distributed along with this file within the software delivery package.
 *
 */

/**
 * \file Ifx_MHA_PatternGen_CYT2B7.h
 * \brief A specialized pattern generator module for CYT2B7x devices.
 * This module sets the compare values needed by the hardware module that drives the switches of the bridge driver, as
 * well as the compare values needed by the hardware module to trigger a current measurement (compare values are mainly
 * calculated by the modulator). It sets the modulation frequency and the deadtime of the system.
 */

#ifndef IFX_MHA_PATTERNGEN_CYT2B7_H
#define IFX_MHA_PATTERNGEN_CYT2B7_H

#include "Ifx_ComponentID.h"
#include "Ifx_ComponentVersion.h"
#include "Ifx_MHA_PatternGen.h"

/**
 * Pattern generator state options
 */
typedef enum Ifx_MHA_PatternGen_CYT2B7_State
{
    Ifx_MHA_PatternGen_CYT2B7_State_init  = 0, /**<Pattern generator is initialized.*/
    Ifx_MHA_PatternGen_CYT2B7_State_off   = 1, /**<Pattern generator is disabled.*/
    Ifx_MHA_PatternGen_CYT2B7_State_on    = 2, /**<Pattern generator is enabled.*/
    Ifx_MHA_PatternGen_CYT2B7_State_fault = 3  /**<Pattern generator is in fault.*/
} Ifx_MHA_PatternGen_CYT2B7_State;

/**
 * Status of the pattern generator, containing the bit coded errors and the state machine state
 */
typedef struct Ifx_MHA_PatternGen_CYT2B7_Status
{
    /**
     * Status of the pattern generator
     */
    Ifx_MHA_PatternGen_CYT2B7_State state;
} Ifx_MHA_PatternGen_CYT2B7_Status;

/**
 * \brief Data structure that stores all data of module instance.
 *
 */
typedef struct Ifx_MHA_PatternGen_CYT2B7
{
    /**
     * Structure inherited from Ifx_MHA_PatternGen
     */
    Ifx_MHA_PatternGen _Super_Ifx_MHA_PatternGen;

    /**
     * Array to store the compare values
     */
    uint16 p_compareValues_tick[6];

    /**
     * Array to store the trigger times values
     */
    uint16 p_triggerTime_tick[2];

    /**
     * Status of the pattern generator, containing the bit coded errors and the state machine state
     */
    Ifx_MHA_PatternGen_CYT2B7_Status p_status;

} Ifx_MHA_PatternGen_CYT2B7;

/**
 *  \brief Handles the state machine of the module.
 *
 *  This API handles the state machine of the module. Additionally, it takes the compare values and the triggers in
 * ticks generated by another block (e.g. space vector modulation) and writes these values to the corresponding hardware
 * configuration registers.
 *
 *  Inputs of this API:
 *  <ul>
 *      <li>State machine "Enable" input, boolean data that is Enabled/Disabled by a call to the
 * Ifx_PatternGen_CYT2B7_enable(true/false)</li>
 *  </ul>
 *
 *  Outputs of this API:
 *  <ul>
 *      <li>State variable: encoded on the "Status" output</li>
 *  </ul>
 *  <ul>
 *      <li>Error code: encoded on the "Status" output</li>
 *  </ul>
 *
 *  These outputs are set corresponding to the states and state transitions design. A fault, if it is not disabled, will
 * be detected and the configured action will be taken within 3 calls to this function.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *  \param [in] compareValues[6] Compare values for the switches: first three up count, second three down count
 *  \param [in] triggerTime_tick[2] Array of first and second time trigger, in clock ticks
 *
 */
void Ifx_MHA_PatternGen_CYT2B7_execute(Ifx_MHA_PatternGen_CYT2B7* self, uint16 compareValues[6], uint16
                                       triggerTime_tick[2]);

/**
 *  \brief Initializes the pattern generator software module.
 *
 *  The peripheral initialization should be done by the user before calling this function.
 *  The timer has to be started by the user before the first call to the module execute function.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 */
void Ifx_MHA_PatternGen_CYT2B7_init(Ifx_MHA_PatternGen_CYT2B7* self);

/**
 *  \brief Get the status of the pattern generator.
 *
 *  The status variable contains the bit coded errors and the state machine state.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \return Pattern generator status
 */
static inline Ifx_MHA_PatternGen_CYT2B7_Status Ifx_MHA_PatternGen_CYT2B7_getStatus(Ifx_MHA_PatternGen_CYT2B7* self)
{
    return self->p_status;
}


/**
 *  \brief Returns the component ID
 *
 *
 *  \param [out] *componentID Variable to store the address of the component ID
 *
 */
void Ifx_MHA_PatternGen_CYT2B7_getID(const Ifx_ComponentID** componentID);

/**
 *  \brief Returns the component version
 *
 *
 *  \param [out] *componentVersion Variable to store the address of the component version
 *
 */
void Ifx_MHA_PatternGen_CYT2B7_getVersion(const Ifx_ComponentVersion** componentVersion);

/**
 *  \brief Clears all faults from the module.
 * The module will be set to enable or disable state in the next call to execute() depending on the enable setting.
 * New hardware fault will lead the module to fault state again.
 *
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \note
 *  Inherited from Ifx_MHA_PatternGen
 */
static inline void Ifx_MHA_PatternGen_CYT2B7_clearFault(Ifx_MHA_PatternGen_CYT2B7* self)
{
    Ifx_MHA_PatternGen_clearFault(&(self->_Super_Ifx_MHA_PatternGen));
}


/**
 *  \brief Check if a clear fault request is pending.
 *
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \return True if a clear fault request was made but still not processed by the module and False otherwise
 *  \note
 *  Inherited from Ifx_MHA_PatternGen
 */
static inline bool Ifx_MHA_PatternGen_CYT2B7_clearFaultIsPending(Ifx_MHA_PatternGen_CYT2B7* self)
{
    return Ifx_MHA_PatternGen_clearFaultIsPending(&(self->_Super_Ifx_MHA_PatternGen));
}


/**
 *  \brief This API enables or disables the module based on the input parameter enable.
 * If the input parameter is TRUE and no fault is detected, then the module will be enabled in the next call to
 * execute().
 * This API also set the HW-related members of the internal "self" data structure to the corresponding HW registers
 * according to the user manual.
 *
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *  \param [in] enable Parameter of boolean type to enable or disable the module
 *
 *  \note
 *  Inherited from Ifx_MHA_PatternGen
 */
static inline void Ifx_MHA_PatternGen_CYT2B7_enable(Ifx_MHA_PatternGen_CYT2B7* self, bool enable)
{
    Ifx_MHA_PatternGen_enable(&(self->_Super_Ifx_MHA_PatternGen), enable);
}


#endif /*IFX_MHA_PATTERNGEN_CYT2B7_H*/
