function modelPath = build_kre_ekf_validation_model(options)
%BUILD_KRE_EKF_VALIDATION_MODEL Build the KRE-to-resolver-EKF harness.
%   The model is intentionally independent from the FOC, FADO, and legacy
%   KRE observer paths. KRE provides active-flux alpha/beta components;
%   FluxEKF normalizes only valid flux vectors and estimates electrical
%   position and speed using resolver_ekf_step.

arguments
    options.ForceRebuild (1, 1) logical = true
end

modelName = 'kre_ekf_validation';
modelDirectory = fileparts(mfilename('fullpath'));
resolverEkfDirectory = fullfile(fileparts(modelDirectory), 'resolver_ekf');
modelPath = fullfile(modelDirectory, [modelName '.slx']);

validate_dependencies(modelDirectory, resolverEkfDirectory);
addpath(modelDirectory);
addpath(resolverEkfDirectory);
configure_file_generation_folders(modelDirectory, modelName);

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

if ~options.ForceRebuild && isfile(modelPath)
    return
end

if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
load_system(modelName);

try
    configure_model(modelName);
    add_validation_blocks(modelName);
    save_system(modelName, modelPath);
catch exception
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end
    rethrow(exception);
end

close_system(modelName, 0);
end

function validate_dependencies(modelDirectory, resolverEkfDirectory)
kreStepPath = fullfile(modelDirectory, 'kre_ekf_kre_step.m');
if ~isfile(kreStepPath)
    error('build_kre_ekf_validation_model:MissingKreStep', ...
        'Missing local KRE step function: %s', kreStepPath);
end

if ~isfolder(resolverEkfDirectory)
    error('build_kre_ekf_validation_model:MissingResolverEkfDirectory', ...
        'Missing resolver EKF directory: %s', resolverEkfDirectory);
end

resolverStepPath = fullfile(resolverEkfDirectory, 'resolver_ekf_step.m');
if ~isfile(resolverStepPath)
    error('build_kre_ekf_validation_model:MissingResolverEkfStep', ...
        'Missing resolver EKF step function: %s', resolverStepPath);
end
end

function configure_file_generation_folders(modelDirectory, modelName)
% Keep generated cache/codegen artifacts outside the repository.
fileGenerationRoot = fullfile(tempdir, [modelName '_filegen']);
cacheFolder = fullfile(fileGenerationRoot, 'cache');
codeGenFolder = fullfile(fileGenerationRoot, 'codegen');

if ~isfolder(cacheFolder)
    mkdir(cacheFolder);
end
if ~isfolder(codeGenFolder)
    mkdir(codeGenFolder);
end

if ~isfolder(modelDirectory)
    error('build_kre_ekf_validation_model:MissingModelDirectory', ...
        'Model directory does not exist: %s', modelDirectory);
end

Simulink.fileGenControl('set', ...
    'CacheFolder', cacheFolder, ...
    'CodeGenFolder', codeGenFolder, ...
    'createDir', true);
end

function configure_model(modelName)
set_param(modelName, ...
    'Solver', 'FixedStepDiscrete', ...
    'SolverType', 'Fixed-step', ...
    'FixedStep', '5e-5', ...
    'StartTime', '0.0', ...
    'StopTime', '0.2', ...
    'SaveTime', 'off', ...
    'SaveOutput', 'off', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'SignalLoggingSaveFormat', 'Dataset');
end

function add_validation_blocks(modelName)
sourceLibrary = 'simulink/Sources/From Workspace';
reshapeLibrary = 'simulink/Math Operations/Reshape';
functionLibrary = 'simulink/User-Defined Functions/MATLAB Function';

add_from_workspace(modelName, sourceLibrary, 'TruePositionPU', ...
    'truePositionPUInput', [30 30 145 60]);
add_from_workspace(modelName, sourceLibrary, 'TrueSpeedPU', ...
    'trueSpeedPUInput', [30 85 145 115]);
add_from_workspace(modelName, sourceLibrary, 'KreEnable', ...
    'kreEnableInput', [30 190 145 220]);
add_from_workspace(modelName, sourceLibrary, 'KreViFb', ...
    'kreViFbInput', [30 245 145 275]);
add_from_workspace(modelName, sourceLibrary, 'KreParams', ...
    'kreParamsInput', [30 300 145 330]);
add_from_workspace(modelName, sourceLibrary, 'KreReset', ...
    'kreResetInput', [30 355 145 385]);
add_from_workspace(modelName, sourceLibrary, 'KrePllParams', ...
    'krePllParamsInput', [30 410 145 440]);

add_block(reshapeLibrary, [modelName '/KreViFbReshape'], ...
    'OutputDimensionality', 'Customize', ...
    'OutputDimensions', '[4 1]', ...
    'Position', [185 245 285 275]);
add_block(reshapeLibrary, [modelName '/KreParamsReshape'], ...
    'OutputDimensionality', 'Customize', ...
    'OutputDimensions', '[14 1]', ...
    'Position', [185 300 285 330]);
add_block(reshapeLibrary, [modelName '/KrePllParamsReshape'], ...
    'OutputDimensionality', 'Customize', ...
    'OutputDimensions', '[2 1]', ...
    'Position', [185 410 285 440]);

add_data_type_conversion(modelName, 'KreEnableCast', 'uint8', ...
    [325 190 415 220]);
add_data_type_conversion(modelName, 'KreViFbCast', 'single', ...
    [325 245 415 275]);
add_data_type_conversion(modelName, 'KreParamsCast', 'single', ...
    [325 300 415 330]);
add_data_type_conversion(modelName, 'KreResetCast', 'uint8', ...
    [325 355 415 385]);
add_data_type_conversion(modelName, 'KrePllParamsCast', 'single', ...
    [325 410 415 440]);

add_block(functionLibrary, [modelName '/KREObserver'], ...
    'Position', [500 225 655 365]);
add_block(functionLibrary, [modelName '/FluxEKF'], ...
    'Position', [770 215 925 370]);

add_to_workspace(modelName, 'LogPositionPUTrue', 'positionPU_true', ...
    [1020 30 1140 60]);
add_to_workspace(modelName, 'LogSpeedPUTrue', 'speedPU_true', ...
    [1020 85 1140 115]);
add_to_workspace(modelName, 'LogKreActiveFluxAlphaWb', ...
    'kre_active_flux_alpha_wb', [1020 170 1140 200]);
add_to_workspace(modelName, 'LogKreActiveFluxBetaWb', ...
    'kre_active_flux_beta_wb', [1020 225 1140 255]);
add_to_workspace(modelName, 'LogKreStatus', 'kre_status', ...
    [1020 280 1140 310]);
add_to_workspace(modelName, 'LogFluxCos', 'ekf_flux_cos', ...
    [1020 345 1140 375]);
add_to_workspace(modelName, 'LogFluxSin', 'ekf_flux_sin', ...
    [1020 400 1140 430]);
add_to_workspace(modelName, 'LogFluxValid', 'ekf_flux_valid', ...
    [1020 455 1140 485]);
add_to_workspace(modelName, 'LogEkfPositionPU', 'ekf_positionPU', ...
    [1020 510 1140 540]);
add_to_workspace(modelName, 'LogEkfSpeedPU', 'ekf_speedPU', ...
    [1020 565 1140 595]);

configure_kre_observer_chart(modelName);
configure_estimator_chart(modelName);

add_named_line(modelName, 'TruePositionPU/1', 'LogPositionPUTrue/1', ...
    'positionPU_true');
add_named_line(modelName, 'TrueSpeedPU/1', 'LogSpeedPUTrue/1', ...
    'speedPU_true');

add_named_line(modelName, 'KreEnable/1', 'KreEnableCast/1', 'kre_enable');
add_named_line(modelName, 'KreViFb/1', 'KreViFbReshape/1', 'kre_vi_fb_raw');
add_named_line(modelName, 'KreViFbReshape/1', 'KreViFbCast/1', 'kre_vi_fb');
add_named_line(modelName, 'KreParams/1', 'KreParamsReshape/1', 'kre_params_raw');
add_named_line(modelName, 'KreParamsReshape/1', 'KreParamsCast/1', 'kre_params');
add_named_line(modelName, 'KreReset/1', 'KreResetCast/1', 'kre_reset');
add_named_line(modelName, 'KrePllParams/1', 'KrePllParamsReshape/1', ...
    'kre_pll_params_raw');
add_named_line(modelName, 'KrePllParamsReshape/1', 'KrePllParamsCast/1', ...
    'kre_pll_params');

add_named_line(modelName, 'KreEnableCast/1', 'KREObserver/1', 'kre_enable');
add_named_line(modelName, 'KreViFbCast/1', 'KREObserver/2', 'kre_vi_fb');
add_named_line(modelName, 'KreParamsCast/1', 'KREObserver/3', 'kre_params');
add_named_line(modelName, 'KreResetCast/1', 'KREObserver/4', 'kre_reset');
add_named_line(modelName, 'KrePllParamsCast/1', 'KREObserver/5', ...
    'kre_pll_params');

add_named_line(modelName, 'KREObserver/1', 'FluxEKF/1', ...
    'activeFluxAlphaWb');
add_named_line(modelName, 'KREObserver/1', 'LogKreActiveFluxAlphaWb/1', ...
    'activeFluxAlphaWb_log');
add_named_line(modelName, 'KREObserver/2', 'FluxEKF/2', ...
    'activeFluxBetaWb');
add_named_line(modelName, 'KREObserver/2', 'LogKreActiveFluxBetaWb/1', ...
    'activeFluxBetaWb_log');
add_named_line(modelName, 'KREObserver/3', 'FluxEKF/3', 'kre_status');
add_named_line(modelName, 'KREObserver/3', 'LogKreStatus/1', ...
    'kre_status_log');
add_named_line(modelName, 'KreResetCast/1', 'FluxEKF/4', ...
    'resolver_reset');

add_named_line(modelName, 'FluxEKF/1', 'LogEkfPositionPU/1', ...
    'ekf_positionPU');
add_named_line(modelName, 'FluxEKF/2', 'LogEkfSpeedPU/1', 'ekf_speedPU');
add_named_line(modelName, 'FluxEKF/3', 'LogFluxCos/1', 'ekf_flux_cos');
add_named_line(modelName, 'FluxEKF/4', 'LogFluxSin/1', 'ekf_flux_sin');
add_named_line(modelName, 'FluxEKF/5', 'LogFluxValid/1', 'ekf_flux_valid');
end

function add_from_workspace(modelName, sourceLibrary, blockName, variableName, position)
add_block(sourceLibrary, [modelName '/' blockName], ...
    'VariableName', variableName, ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', position);
end

function add_to_workspace(modelName, blockName, variableName, position)
add_block('simulink/Sinks/To Workspace', [modelName '/' blockName], ...
    'VariableName', variableName, ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', position);
end

function add_data_type_conversion(modelName, blockName, outputType, position)
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [modelName '/' blockName], ...
    'OutDataTypeStr', outputType, ...
    'Position', position);
end

function add_named_line(modelName, source, destination, signalName)
lineHandle = add_line(modelName, source, destination, 'autorouting', 'on');
set_param(lineHandle, 'Name', signalName);
end

function configure_kre_observer_chart(modelName)
root = sfroot;
chart = root.find('-isa', 'Stateflow.EMChart', ...
    'Path', [modelName '/KREObserver']);
if isempty(chart)
    error('build_kre_ekf_validation_model:MissingKreFunctionBlock', ...
        'Could not locate the KREObserver MATLAB Function block.');
end

chart = chart(1);
chart.Script = sprintf([ ...
    'function [active_flux_alpha_wb, active_flux_beta_wb, kre_status] = ...\n' ...
    '    KREObserver(kre_enable, kre_vi_fb, kre_params, kre_reset, kre_pll_params)\n' ...
    '%%#codegen\n' ...
    'persistent state\n' ...
    'if isempty(state)\n' ...
    '    state = zeros(18, 1, ''single'');\n' ...
    'end\n' ...
    '[state, active_flux_alpha_wb, active_flux_beta_wb, kre_status] = ...\n' ...
    '    kre_ekf_kre_step(state, kre_enable, kre_vi_fb, kre_params, ...\n' ...
    '    kre_reset, kre_pll_params);\n' ...
    'end\n']);
end

function configure_estimator_chart(modelName)
root = sfroot;
chart = root.find('-isa', 'Stateflow.EMChart', ...
    'Path', [modelName '/FluxEKF']);
if isempty(chart)
    error('build_kre_ekf_validation_model:MissingFunctionBlock', ...
        'Could not locate the FluxEKF MATLAB Function block.');
end

chart = chart(1);
chart.Script = sprintf([ ...
    'function [positionPU, speedPU, fluxCos, fluxSin, fluxValid] = ...\n' ...
    '    FluxEKF(activeFluxAlphaWb, activeFluxBetaWb, kreStatus, reset)\n' ...
    '%%#codegen\n' ...
    'persistent state initialized positionHold speedHold\n' ...
    'if isempty(state)\n' ...
    '    state = zeros(3, 1);\n' ...
    '    initialized = false;\n' ...
    '    positionHold = 0;\n' ...
    '    speedHold = 0;\n' ...
    'end\n' ...
    'fluxCos = 0;\n' ...
    'fluxSin = 0;\n' ...
    'fluxValid = uint8(0);\n' ...
    'if reset ~= 0\n' ...
    '    state = zeros(3, 1);\n' ...
    '    initialized = false;\n' ...
    '    positionHold = 0;\n' ...
    '    speedHold = 0;\n' ...
    'end\n' ...
    'if kreStatus == uint8(1)\n' ...
    '    fluxAlpha = double(activeFluxAlphaWb);\n' ...
    '    fluxBeta = double(activeFluxBetaWb);\n' ...
    '    fluxMagnitude = sqrt(fluxAlpha * fluxAlpha + fluxBeta * fluxBeta);\n' ...
    '    if isfinite(fluxMagnitude) && fluxMagnitude > 0\n' ...
    '        fluxCos = fluxAlpha / fluxMagnitude;\n' ...
    '        fluxSin = fluxBeta / fluxMagnitude;\n' ...
    '        [state, positionHold, speedHold] = resolver_ekf_step( ...\n' ...
    '            state, fluxCos, fluxSin, ~initialized, resolver_ekf_config);\n' ...
    '        initialized = true;\n' ...
    '        fluxValid = uint8(1);\n' ...
    '    end\n' ...
    'end\n' ...
    'positionPU = positionHold;\n' ...
    'speedPU = speedHold;\n' ...
    'end\n']);

configData = Stateflow.Data(chart);
configData.Name = 'resolver_ekf_config';
configData.Scope = 'Parameter';
configData.DataType = 'Inherit: Same as Simulink';
end
