function report = verify_apsfsm_ert_replay(tccExecutable)
%verify_apsfsm_ert_replay Compile and replay generated wrapper ERT C.
%
% Pass a TinyCC executable explicitly, or set APSFSM_TCC_EXE. The compiler
% is used only in a temporary directory to run the generated host replay.

if nargin < 1 || strlength(string(tccExecutable)) == 0
    tccExecutable = getenv('APSFSM_TCC_EXE');
end
tccExecutable = char(tccExecutable);
assert(isfile(tccExecutable), 'APSFSM:MissingCompiler', ...
    ['A TinyCC executable is required for host ERT replay. Pass it as ' ...
    'an argument or set APSFSM_TCC_EXE.']);

algorithmDirectory = fileparts(mfilename('fullpath'));
generatedDirectory = fullfile(algorithmDirectory, ...
    'apsfsm_torque_compensation_wrapper_ert_rtw');
testDataFile = fullfile(algorithmDirectory, 'testdata', ...
    'apsfsm_source_replay_vectors.mat');
requiredFiles = {
    fullfile(generatedDirectory, 'apsfsm_torque_compensation_wrapper.c')
    fullfile(generatedDirectory, 'apsfsm_torque_compensation_wrapper.h')
    fullfile(generatedDirectory, 'rt_nonfinite.c')
    fullfile(algorithmDirectory, 'apsfsm_ert_nonfinite_host.c')
    fullfile(algorithmDirectory, 'apsfsm_ert_math_host.c')
    fullfile(algorithmDirectory, 'apsfsm_ert_replay_bridge.c')
    fullfile(algorithmDirectory, 'apsfsm_ert_replay_main.c')};
for fileIndex = 1:numel(requiredFiles)
    assert(isfile(requiredFiles{fileIndex}), ...
        'APSFSM:MissingErtFile', 'Missing ERT replay input: %s', ...
        requiredFiles{fileIndex});
end

buildDirectory = tempname;
mkdir(buildDirectory);
cleanupDirectory = onCleanup(@() localCleanup(buildDirectory));
vectorFile = fullfile(buildDirectory, 'apsfsm_ert_replay_vectors.bin');
executableFile = fullfile(buildDirectory, 'apsfsm_ert_replay.exe');
localWriteReplayVectors(testDataFile, vectorFile);

compileCommand = sprintf([ ...
    '"%s" -Wall -I"%s" -I"%s" -o "%s" ' ...
    '"%s" "%s" "%s" "%s" "%s"'], ...
    tccExecutable, algorithmDirectory, generatedDirectory, executableFile, ...
    fullfile(algorithmDirectory, 'apsfsm_ert_replay_main.c'), ...
    fullfile(algorithmDirectory, 'apsfsm_ert_replay_bridge.c'), ...
    fullfile(generatedDirectory, 'apsfsm_torque_compensation_wrapper.c'), ...
    fullfile(algorithmDirectory, 'apsfsm_ert_nonfinite_host.c'), ...
    fullfile(algorithmDirectory, 'apsfsm_ert_math_host.c'));
[compileStatus, compileOutput] = system(compileCommand);
assert(compileStatus == 0, 'APSFSM:ErtCompileFailed', ...
    'ERT host compilation failed:\n%s', compileOutput);

[replayStatus, replayOutput] = system(sprintf('"%s" "%s"', ...
    executableFile, vectorFile));
assert(replayStatus == 0, 'APSFSM:ErtReplayFailed', ...
    'ERT host replay failed:\n%s', replayOutput);
values = sscanf(replayOutput, ...
    'ERT replay: samples=%u max_state=%f max_diag=%f finite=%u');
assert(numel(values) == 4, 'APSFSM:ErtReplayOutput', ...
    'Unexpected ERT replay output:\n%s', replayOutput);

report = struct( ...
    'sampleCount', uint32(values(1)), ...
    'maximumStateError_PU', single(values(2)), ...
    'maximumDiagnosticError_PU', single(values(3)), ...
    'allFinite', logical(values(4)), ...
    'passed', true);
fprintf('%s', replayOutput);
clear cleanupDirectory;
end

function localWriteReplayVectors(testDataFile, vectorFile)
replay = load(testDataFile);
source = replay.source;
parameters = single([source.omegaBase_radps; source.kHat; ...
    source.rho_rad; source.lambda; source.coefficientLimit_PU]);
sampleCount = numel(replay.speedFeedback_PU);
records = zeros(sampleCount + 2, 19, 'single');
referenceState = zeros(4, 1, 'single');

for sampleIndex = 1:sampleCount
    learnEnable = single(replay.learnEnable_u8(sampleIndex));
    control = single([learnEnable; 0; 1 - learnEnable]);
    [referenceState, referenceDiagnostics] = ...
        apsfsmTorqueCompensationStep(referenceState, ...
        replay.speedReference_PU(sampleIndex), ...
        replay.speedFeedback_PU(sampleIndex), parameters, control);
    records(sampleIndex, :) = single([sampleIndex == 1; ...
        replay.speedReference_PU(sampleIndex); ...
        replay.speedFeedback_PU(sampleIndex); parameters; control; ...
        referenceState; referenceDiagnostics]).';
end

invalidParameters = parameters;
invalidParameters(4) = single(NaN);
[invalidState, invalidDiagnostics] = apsfsmTorqueCompensationStep( ...
    zeros(4, 1, 'single'), single(0.2), single(0.2), ...
    invalidParameters, single([1; 0; 0]));
records(sampleCount + 1, :) = single([1; 0.2; 0.2; ...
    invalidParameters; 1; 0; 0; invalidState; invalidDiagnostics]).';

[invalidInputState, invalidInputDiagnostics] = ...
    apsfsmTorqueCompensationStep(zeros(4, 1, 'single'), single(NaN), ...
    single(0.2), parameters, single([1; 0; 0]));
records(sampleCount + 2, :) = single([1; NaN; 0.2; parameters; 1; 0; 0; ...
    invalidInputState; invalidInputDiagnostics]).';

fileIdentifier = fopen(vectorFile, 'wb');
assert(fileIdentifier >= 0, 'APSFSM:VectorFileOpen', ...
    'Unable to create ERT replay vector file: %s', vectorFile);
cleanupFile = onCleanup(@() fclose(fileIdentifier));
fwrite(fileIdentifier, uint32(size(records, 1)), 'uint32');
fwrite(fileIdentifier, records.', 'single');
clear cleanupFile;
end

function localCleanup(buildDirectory)
if isfolder(buildDirectory)
    rmdir(buildDirectory, 's');
end
end
