function powerfitDatabase = powerfit_empty_database()
%POWERFIT_EMPTY_DATABASE Create the versioned, append-only database schema.

powerfitDatabase = struct();
powerfitDatabase.SchemaVersion = "1.0";
powerfitDatabase.CreatedAt = datetime("now");
powerfitDatabase.UpdatedAt = NaT;
sampleNames = [ ...
    "SourceId", "SourceFile", "TestId", ...
    "FitGroupId", "HardwareConfigId", "FirmwareId", "MotorId", "InverterId", ...
    "SwitchingFrequency_Hz", "CoolantTemperature_C", ...
    "SampleTime_s", "SupplyVoltageRaw", "SupplyCurrentRaw", ...
    "SupplyVoltage_V", "SupplyCurrent_A", "PdcMeasured_W", ...
    "Vd_V", "Vq_V", "Id_A", "Iq_A", "FocVdc_V", "Speed_rpm", "FocState", ...
    "SupplyVoltageSyncDistance_s", "SupplyCurrentSyncDistance_s", ...
    "FocVdcSyncDistance_s", "SpeedSyncDistance_s", "FocStateSyncDistance_s", ...
    "Pdq_W", "CurrentSq_A2", "Irms_A", "Speed_pu", ...
    "BasisCopper_W", "BasisIron_W", "BasisInvCond_W", "BasisInvSwitch_W", ...
    "TargetLoss_W", "ImportValid", "TimeAligned", "SteadyState", "FitEligible", ...
    "ExcludeReason"];
sampleTypes = [ ...
    repmat("string", 1, 8), repmat("double", 1, 29), ...
    repmat("logical", 1, 4), "string"];
powerfitDatabase.Samples = table( ...
    'Size', [0, numel(sampleNames)], ...
    'VariableTypes', cellstr(sampleTypes), ...
    'VariableNames', cellstr(sampleNames));

manifestNames = [ ...
    "SourceId", "SourceHashSHA256", "SourceFile", "TestId", ...
    "FileBytes", "ModifiedTime", "MdfVersion", "MdfInitialTimestamp", ...
    "FitGroupId", "HardwareConfigId", "FirmwareId", "MotorId", "InverterId", ...
    "SwitchingFrequency_Hz", "CoolantTemperature_C", ...
    "SupplyVoltageScaleConfirmed", "SupplyCurrentPolarityConfirmed", ...
    "DqCurrentMatchesFirmware", "SupplyVoltageScale_V_per_value", ...
    "SupplyCurrentScale_A_per_value", ...
    "DqGroup", "DcVoltageGroup", "DcCurrentGroup", "FocStateGroup", ...
    "FocVdcGroup", "SpeedGroup", "RowsRead", "EligibleRows", ...
    "SupplyVsFocVdcMean_V", "SupplyVsFocVdcMeanAbs_V", "SupplyVsFocVdcMaxAbs_V", ...
    "Status", "Reason", "ImportedAt"];
manifestTypes = [ ...
    repmat("string", 1, 4), "double", "datetime", "string", "datetime", ...
    repmat("string", 1, 5), repmat("double", 1, 2), repmat("logical", 1, 3), ...
    repmat("double", 1, 13), "string", "string", "datetime"];
powerfitDatabase.Manifest = table( ...
    'Size', [0, numel(manifestNames)], ...
    'VariableTypes', cellstr(manifestTypes), ...
    'VariableNames', cellstr(manifestNames));
end
