function [Ad,Bd,Cd,Dd] = dv_coefficients_ZOH(smoke_T)
%dv_coefficients_ZOH
%    [Ad,Bd,Cd,Dd] = dv_coefficients_ZOH(smoke_T)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026-09-10 22:41:12

t2 = smoke_T.*2.0;
t3 = -t2;
t4 = exp(t3);
Ad = t4;
if nargout > 1
    Bd = t4.*(-1.0./2.0)+1.0./2.0;
end
if nargout > 2
    Cd = 1.0;
end
if nargout > 3
    Dd = 0.0;
end
end
