function [b,a] = dv_io_coefficients_Tustin_o1_i1(smoke_T)
%dv_io_coefficients_Tustin_o1_i1
%    [B,A] = dv_io_coefficients_Tustin_o1_i1(smoke_T)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026-09-10 22:40:48

t2 = smoke_T+2.0;
t3 = 1.0./t2;
t4 = smoke_T.*t3;
b = [t4,t4];
if nargout > 1
    a = [1.0,t3.*(smoke_T-2.0)];
end
end
