function [probeD_PU, probeQ_PU, rs_Ohm, ld_H, lq_H, fluxPM_Wb, ...
    estimateValid, freshEstimate, staleEstimate, status, ...
    conditionNumber, relativeResidual, consecutiveAcceptedWindows, ...
    windowSampleCount] = vafid_external_observer_wrapper_step( ...
    mode, resetRequest, sampleValid, voltageAlpha_V, voltageBeta_V, ...
    currentAlpha_A, currentBeta_A, kreElectricalAngle_rad, ...
    kreElectricalOmega_radps, kreActiveFlux_Wb, configValues)
%VAFID_EXTERNAL_OBSERVER_WRAPPER_STEP Fixed-size ERT wrapper entry point.
%   CONFIGVALUES is a 30-by-1 single vector produced by
%   vafid_pack_wrapper_config. Keeping the model interface numeric avoids a
%   workspace-owned Simulink.Bus while preserving the reference function's
%   strongly typed configuration structure.

%#codegen

config = localUnpackConfig(configValues);
[probeD_PU, probeQ_PU, rs_Ohm, ld_H, lq_H, fluxPM_Wb, ...
    estimateValid, freshEstimate, staleEstimate, status, ...
    conditionNumber, relativeResidual, consecutiveAcceptedWindows, ...
    windowSampleCount] = vafid_discrete_reference_step( ...
    mode, resetRequest, sampleValid, voltageAlpha_V, voltageBeta_V, ...
    currentAlpha_A, currentBeta_A, kreElectricalAngle_rad, ...
    kreElectricalOmega_radps, kreActiveFlux_Wb, config);
end

function config = localUnpackConfig(values)
config = struct( ...
    'sampleTime_s', values(1), ...
    'probeD_Frequency_Hz', values(2), ...
    'probeQ_Frequency_Hz', values(3), ...
    'probeD_Amplitude_PU', values(4), ...
    'probeQ_Amplitude_PU', values(5), ...
    'probeD_MaxAmplitude_PU', values(6), ...
    'probeQ_MaxAmplitude_PU', values(7), ...
    'settleTime_s', values(8), ...
    'windowLength_samples', uint32(values(9)), ...
    'omegaLpf_Hz', values(10), ...
    'angleTrack_Hz', values(11), ...
    'activeFluxLpf_Hz', values(12), ...
    'parameterFusion', values(13), ...
    'fluxFusion', values(14), ...
    'conditionLimit', values(15), ...
    'relativeResidualLimit', values(16), ...
    'requiredAcceptedWindows', uint16(values(17)), ...
    'staleRejectedWindows', uint16(values(18)), ...
    'nominalRs_Ohm', values(19), ...
    'nominalLd_H', values(20), ...
    'nominalLq_H', values(21), ...
    'nominalFluxPM_Wb', values(22), ...
    'minimumRs_Ohm', values(23), ...
    'maximumRs_Ohm', values(24), ...
    'minimumLd_H', values(25), ...
    'maximumLd_H', values(26), ...
    'minimumLq_H', values(27), ...
    'maximumLq_H', values(28), ...
    'minimumFluxPM_Wb', values(29), ...
    'maximumFluxPM_Wb', values(30));
end
