function config = vafid_default_config()
%VAFID_DEFAULT_CONFIG Project defaults for the VAFID discrete reference.
%   All floating-point values are single precision so the same configuration
%   can be used by MATLAB Coder and by the future independent wrapper model.

%#codegen

config = struct( ...
    'sampleTime_s', single(50e-6), ...
    'probeD_Frequency_Hz', single(150.0), ...
    'probeQ_Frequency_Hz', single(220.0), ...
    'probeD_Amplitude_PU', single(0.005), ...
    'probeQ_Amplitude_PU', single(0.005), ...
    'probeD_MaxAmplitude_PU', single(0.015), ...
    'probeQ_MaxAmplitude_PU', single(0.010), ...
    'settleTime_s', single(0.250), ...
    'windowLength_samples', uint32(2000), ...
    'omegaLpf_Hz', single(25.0), ...
    'angleTrack_Hz', single(8.0), ...
    'activeFluxLpf_Hz', single(25.0), ...
    'parameterFusion', single(0.20), ...
    'fluxFusion', single(0.35), ...
    'conditionLimit', single(1.0e4), ...
    'relativeResidualLimit', single(0.65), ...
    'requiredAcceptedWindows', uint16(3), ...
    'staleRejectedWindows', uint16(3), ...
    'nominalRs_Ohm', single(0.50), ...
    'nominalLd_H', single(1.30e-3), ...
    'nominalLq_H', single(1.38e-3), ...
    'nominalFluxPM_Wb', single(46.0e-3), ...
    'minimumRs_Ohm', single(0.05), ...
    'maximumRs_Ohm', single(3.00), ...
    'minimumLd_H', single(0.10e-3), ...
    'maximumLd_H', single(20.0e-3), ...
    'minimumLq_H', single(0.10e-3), ...
    'maximumLq_H', single(20.0e-3), ...
    'minimumFluxPM_Wb', single(5.0e-3), ...
    'maximumFluxPM_Wb', single(0.20));
end
