% HFO virtual-flux observer profile.
% This script runs after the selected SPMSM/IPMSM profile is complete and
% always creates the observer parameter vector, independent of selector 4.

if ~exist('pmsm', 'var') || ~exist('inverter', 'var') || ...
        ~exist('PU_System', 'var')
    error('HFO setup requires the motor profile to be initialized first.');
end
if ~exist('FOCutOffFrq', 'var') || ~exist('FOSpdCutOffFrq', 'var')
    error('HFO setup requires the Flux Observer cutoff frequencies.');
end

if ~exist('KRE_OBSERVER_R_RATIO', 'var')
    KRE_OBSERVER_R_RATIO = single(1);
end

RsEff = KRE_OBSERVER_R_RATIO * motor.Rs;
Kinj = single(0.1);
Kob = single(2 * pi * FOCutOffFrq);
SpeedFilterHz = single(FOSpdCutOffFrq);

HFO_Profile = struct( ...
    'RsEff', single(RsEff), ...
    'Kob', Kob, ...
    'Kinj', Kinj, ...
    'SpeedFilterHz', SpeedFilterHz, ...
    'PsiDInjection', single(-Kinj * pmsm.FluxPM), ...
    'PsiQInjection', single(Kinj * pmsm.FluxPM));

HFO_Params_Vector = single([ ...
    RsEff; ...
    pmsm.Ld; ...
    pmsm.Lq; ...
    pmsm.FluxPM; ...
    Ts; ...
    PU_System.V_base; ...
    PU_System.I_base; ...
    pmsm.N_base; ...
    pmsm.p; ...
    Kob; ...
    Kinj; ...
    SpeedFilterHz]);

% Equation (30) at zero current reduces to 1-Kinj > 0. Keep this as a
% diagnostic value for the focused runner; it is not a mode-switch limit.
HFO_Eq30Margin = single(1 - Kinj);
HFO_PsiDInjection = HFO_Profile.PsiDInjection;
HFO_PsiQInjection = HFO_Profile.PsiQInjection;
HFO_Active = logical(exist('estimatorSelection', 'var') && ...
    estimatorSelection == 4);

if ~(HFO_PsiQInjection ~= 0 && HFO_PsiDInjection < 0 && HFO_Eq30Margin > 0)
    error('HFO virtual-flux injection violates the zero-current stability checks.');
end
