function [speedPU, posPU] = mcb_pmsm_foc_sensorless_f28379d_kre_observer_step(viFb, params, pllParams)
%#codegen
% Discrete KRE active-flux observer from the paper, with a project-side
% angle-to-speed adapter. viFb is [Valpha_PU Vbeta_PU Ialpha_PU Ibeta_PU].

persistent h2Vri h2I h2Reg h2D qState yState lambdaHat pllTheta pllOmegaInt speedFilt pllInitialized

if isempty(pllInitialized)
    sample = viFb(1);
    h2Vri = zeros(2, 1, 'like', sample);
    h2I = zeros(2, 1, 'like', sample);
    h2Reg = zeros(1, 1, 'like', sample);
    h2D = zeros(1, 1, 'like', sample);
    qState = zeros(2, 2, 'like', sample);
    yState = zeros(2, 1, 'like', sample);
    lambdaHat = zeros(2, 1, 'like', sample);
    pllTheta = zeros(1, 1, 'like', sample);
    pllOmegaInt = zeros(1, 1, 'like', sample);
    speedFilt = zeros(1, 1, 'like', sample);
    pllInitialized = false;
end

resistance = params(1);
ld = params(2);
lq = params(3);
psiM = params(4);
sampleTime = params(5);
voltageBase = params(6);
currentBase = params(7);
speedBase = params(8);
polePairs = params(9);
alpha = params(10);
aGain = params(11);
gamma = params(12);
sigmaEpsilon = params(13);
speedFilterHz = params(14);
pllBandwidthHz = pllParams(1);
pllDamping = pllParams(2);

voltageAB = [viFb(1); viFb(2)] * voltageBase;
currentAB = [viFb(3); viFb(4)] * currentBase;
l0 = ld - lq;

% Exact zero-order-hold discretization of H2 = alpha/(p + alpha).
h2Gain = 1 - exp(-alpha * sampleTime);
vri = voltageAB - resistance * currentAB;
h2Vri = h2Vri + h2Gain * (vri - h2Vri);
h2I = h2I + h2Gain * (currentAB - h2I);
h1I = alpha * (currentAB - h2I);

omega1 = h2Vri - lq * h1I;
omega2 = omega1 - l0 * h1I;
phi = omega1 + omega2;

regressionProduct = omega2(1) * omega1(1) + omega2(2) * omega1(2);
h2Reg = h2Reg + h2Gain * (regressionProduct - h2Reg);
regressionY = l0 * (h2I(1) * omega1(1) + h2I(2) * omega1(2)) + ...
    (omega1(1) * omega1(1) + omega1(2) * omega1(2)) / alpha + h2Reg / alpha;

xHat = lambdaHat - lq * currentAB;
xNorm = sqrt(xHat(1) * xHat(1) + xHat(2) * xHat(2));
if xNorm >= sigmaEpsilon
    sigmaX = xHat / xNorm;
else
    sigmaX = zeros(2, 1, 'like', xHat);
end

dInput = currentAB(1) * sigmaX(1) + currentAB(2) * sigmaX(2);
h2D = h2D + h2Gain * (dInput - h2D);
dHat = -psiM * l0 * alpha * (dInput - h2D);

estimationError = phi(1) * xHat(1) + phi(2) * xHat(2) + dHat - regressionY;
correction = -gamma * yState;
qDot = -aGain * (qState - phi * phi.');
yDot = -aGain * (yState - phi * estimationError) + qState * correction;
lambdaDot = voltageAB - resistance * currentAB + correction;

qState = qState + sampleTime * qDot;
yState = yState + sampleTime * yDot;
lambdaHat = lambdaHat + sampleTime * lambdaDot;

% atan2 provides the KRE active-flux phase measurement. The FOC-facing
% angle and speed are generated by the Type-II PLL below, not by a direct
% angle derivative.
thetaRaw = atan2(xHat(2), xHat(1));

if xNorm >= sigmaEpsilon
    if pllInitialized
        phaseError = thetaRaw - pllTheta;
        if phaseError > pi
            phaseError = phaseError - 2 * pi;
        elseif phaseError < -pi
            phaseError = phaseError + 2 * pi;
        end

        pllNaturalFrequency = 2 * pi * pllBandwidthHz;
        pllKp = 2 * pllDamping * pllNaturalFrequency;
        pllKi = pllNaturalFrequency * pllNaturalFrequency;
        pllOmegaInt = pllOmegaInt + sampleTime * pllKi * phaseError;
        pllOmega = pllOmegaInt + pllKp * phaseError;
        pllTheta = pllTheta + sampleTime * pllOmega;

        if pllTheta > pi
            pllTheta = pllTheta - 2 * pi;
        elseif pllTheta < -pi
            pllTheta = pllTheta + 2 * pi;
        end
    else
        % Use the first credible KRE flux direction as the PLL phase seed.
        pllTheta = thetaRaw;
        pllOmegaInt = zeros(1, 1, 'like', thetaRaw);
        pllOmega = zeros(1, 1, 'like', thetaRaw);
        pllInitialized = true;
    end
else
    % Keep the last PLL state while the active-flux vector is too small.
    pllOmega = pllOmegaInt;
end

if pllInitialized
    if pllTheta < 0
        posPU = pllTheta / (2 * pi) + 1;
    else
        posPU = pllTheta / (2 * pi);
    end
    speedRaw = pllOmega * 60 / (2 * pi * polePairs * speedBase);
else
    posPU = zeros(1, 1, 'like', thetaRaw);
    speedRaw = zeros(1, 1, 'like', thetaRaw);
end

speedGain = 1 - exp(-2 * pi * speedFilterHz * sampleTime);
speedFilt = speedFilt + speedGain * (speedRaw - speedFilt);
speedPU = speedFilt;
end