function result = test_fado_foc_conversion_vectors()
%TEST_FADO_FOC_CONVERSION_VECTORS Check the C-side FADO-to-FOC mappings.

twoPi = single(6.2831855);
angleIndexPerRad = single(683565312.0);
epsilonRad = single(1e-4);
angles_rad = single([-twoPi, -twoPi + epsilonRad, -single(pi), -epsilonRad, ...
    0, epsilonRad, single(pi), twoPi - epsilonRad, twoPi, 2 * twoPi, ...
    100 * single(pi) + single(0.3)]);

wrappedAngle_rad = rem(angles_rad, twoPi);
wrappedAngle_rad(wrappedAngle_rad < 0) = ...
    wrappedAngle_rad(wrappedAngle_rad < 0) + twoPi;
wrappedAngle_rad(wrappedAngle_rad >= twoPi) = single(0);
angleIndex = uint32(floor(double(wrappedAngle_rad) .* double(angleIndexPerRad)));

assert(all(isfinite(wrappedAngle_rad)));
assert(all(wrappedAngle_rad >= 0 & wrappedAngle_rad < twoPi));
assert(wrappedAngle_rad(1) == 0 && wrappedAngle_rad(5) == 0 ...
    && wrappedAngle_rad(9) == 0 && wrappedAngle_rad(10) == 0);
assert(wrappedAngle_rad(2) == angles_rad(2) + twoPi);
assert(wrappedAngle_rad(4) == twoPi - epsilonRad);
assert(wrappedAngle_rad(6) == epsilonRad ...
    && wrappedAngle_rad(8) == twoPi - epsilonRad);
assert(angleIndex(1) == 0 && angleIndex(5) == 0 ...
    && angleIndex(9) == 0 && angleIndex(10) == 0);

baseSpeed_rpm = single(8500);
mechanicalSpeed_rpm = single([-17000, -8500, -4250, -1, 0, 1, ...
    4250, 8499.9, 8500, 17000]);
rawQ15 = fix(double((mechanicalSpeed_rpm / baseSpeed_rpm) * single(32768)));
speedQ15 = min(max(rawQ15, -32768), 32767);
expectedSpeedQ15 = [-32768, -32768, -16384, -3, 0, 3, 16384, ...
    32767, 32767, 32767];
assert(isequal(speedQ15, expectedSpeedQ15));

result = struct( ...
    'angleCaseCount', numel(angles_rad), ...
    'speedCaseCount', numel(mechanicalSpeed_rpm), ...
    'angleIndex', angleIndex, ...
    'speedQ15', speedQ15);

fprintf(['FADO FOC conversion vectors PASS: %d angle cases, %d rpm cases; ' ...
    'index range [%u, %u], q15 range [%d, %d].\n'], ...
    result.angleCaseCount, result.speedCaseCount, min(angleIndex), max(angleIndex), ...
    min(speedQ15), max(speedQ15));
end
