function [b,a] = dv_io_coefficients_TustinPrewarp_o1_i1(dv_test_K,dv_test_tau,dv_test_T,dv_test_wp)
%dv_io_coefficients_TustinPrewarp_o1_i1
%    [B,A] = dv_io_coefficients_TustinPrewarp_o1_i1(dv_test_K,DV_TEST_TAU,dv_test_T,DV_TEST_WP)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026-09-10 22:31:27

t2 = dv_test_wp.*dv_test_tau;
t3 = (dv_test_T.*dv_test_wp)./2.0;
t4 = tan(t3);
t5 = t2+t4;
t6 = 1.0./t5;
t7 = dv_test_K.*t4.*t6;
b = [t7,t7];
if nargout > 1
    a = [1.0,-t6.*(t2-t4)];
end
end
