function report = run_fado_regression()
%RUN_FADO_REGRESSION Run the FADO and Flux Observer acceptance scenarios.
% Uses model-internal Step sources and SimulationInput so the saved model is
% never modified by a regression run.

model = 'mcb_pmsm_foc_sensorless_f28379d';
mcb_pmsm_foc_sensorless_f28379d_datascript;
mcb_pmsm_foc_sensorless_f28379d_fado_init;

% Check that the documented forward-Euler form remains well posed.
equations = fado_discrete_equations(fado, 0);
assert(all(isfinite(equations.Observer.Ad), 'all'));

selector_path = Simulink.ID.getFullName([model ':7835']);
speed_step_path = Simulink.ID.getFullName([model ':8929']);
load_step_path = Simulink.ID.getFullName([model ':8930']);
id_assist_enable_path = Simulink.ID.getFullName([model ':9010']);
id_assist_imin_path = Simulink.ID.getFullName([model ':9011']);
fado_config_path = Simulink.ID.getFullName([model ':9012']);

scenarios = localScenarios();
report = repmat(localEmptyResult(), numel(scenarios), 1);

for k = 1:numel(scenarios)
    scenario = scenarios(k);
    in = Simulink.SimulationInput(model);
    in = in.setModelParameter('StopTime', '8', 'ReturnWorkspaceOutputs', 'on');
    in = in.setBlockParameter(selector_path, 'Value', sprintf('uint32(%d)', scenario.Selector));
    in = in.setBlockParameter(speed_step_path, ...
        'InitialValue', scenario.SpeedInitial, ...
        'FinalValue', scenario.SpeedFinal, ...
        'Time', scenario.SpeedStepTime);
    in = in.setBlockParameter(load_step_path, ...
        'InitialValue', scenario.LoadInitial, ...
        'FinalValue', scenario.LoadFinal, ...
        'Time', scenario.LoadStepTime);
    in = in.setBlockParameter(id_assist_enable_path, 'Value', scenario.IdAssistEnable);
    in = in.setBlockParameter(id_assist_imin_path, 'Value', 'single(fado_IminPU)');
    in = in.setBlockParameter(fado_config_path, 'Value', ...
        localFadoConfigExpression(scenario.RsScale, scenario.LqScale));

    out = sim(in);
    report(k) = localAnalyzeScenario(out, scenario);
end

report_file = fullfile(fileparts(mfilename('fullpath')), 'fado_regression_results.mat');
save(report_file, 'report', 'scenarios', 'equations');
localPrintReport(report);
end

function scenarios = localScenarios()
scenarios = [ ...
    localScenario('FluxObserver_Default', 1, '0.1*pmsm.N_base', '0.6*pmsm.N_base', '1', '0', '0.05*pmsm.T_rated', '3', 'single(0)', 1, 1), ...
    localScenario('FADO_Default', 3, '0.1*pmsm.N_base', '0.6*pmsm.N_base', '1', '0', '0.05*pmsm.T_rated', '3', 'single(0)', 1, 1), ...
    localScenario('FADO_Reversal', 3, '0.1*pmsm.N_base', '-0.6*pmsm.N_base', '1', '0', '0.05*pmsm.T_rated', '3', 'single(0)', 1, 1), ...
    localScenario('FADO_ZeroHold_IdAssist', 3, '0', '0', '1', '0', '0', '3', 'single(1)', 1, 1), ...
    localScenario('FADO_RsMinus20', 3, '0.1*pmsm.N_base', '0.6*pmsm.N_base', '1', '0', '0.05*pmsm.T_rated', '3', 'single(0)', 0.8, 1), ...
    localScenario('FADO_RsPlus20', 3, '0.1*pmsm.N_base', '0.6*pmsm.N_base', '1', '0', '0.05*pmsm.T_rated', '3', 'single(0)', 1.2, 1), ...
    localScenario('FADO_LqMinus20', 3, '0.1*pmsm.N_base', '0.6*pmsm.N_base', '1', '0', '0.05*pmsm.T_rated', '3', 'single(0)', 1, 0.8), ...
    localScenario('FADO_LqPlus20', 3, '0.1*pmsm.N_base', '0.6*pmsm.N_base', '1', '0', '0.05*pmsm.T_rated', '3', 'single(0)', 1, 1.2)];
end

function scenario = localScenario(name, selector, speed_initial, speed_final, speed_time, load_initial, load_final, load_time, id_assist_enable, rs_scale, lq_scale)
scenario = struct( ...
    'Name', name, ...
    'Selector', selector, ...
    'SpeedInitial', speed_initial, ...
    'SpeedFinal', speed_final, ...
    'SpeedStepTime', speed_time, ...
    'LoadInitial', load_initial, ...
    'LoadFinal', load_final, ...
    'LoadStepTime', load_time, ...
    'IdAssistEnable', id_assist_enable, ...
    'RsScale', rs_scale, ...
    'LqScale', lq_scale);
end

function expression = localFadoConfigExpression(rs_scale, lq_scale)
expression = sprintf(['single([fado_Rs %.17g fado_Lq %.17g fado_PolePairs ' ...
    'fado_Ts fado_VBase fado_IBase fado_NBase fado_FluxLimit fado_Kdf ' ...
    'fado_LowSpeedHz fado_Kaf fado_T2SFastBandwidthHz ' ...
    'fado_T2SSlowBandwidthHz fado_Zeta fado_EnableVoltagePreprocess ' ...
    'fado_VAlphaPreprocess fado_VBetaPreprocess])'], rs_scale, lq_scale);
end

function result = localAnalyzeScenario(out, scenario)
required = {'Pos_PU_est', 'speed_PU_est', 'Pos_PU_true', ...
    'FADO_lambda_alpha1', 'FADO_lambda_beta1', 'FADO_lambda_alpha2', ...
    'FADO_lambda_beta2', 'FADO_Dhat_alpha', 'FADO_Dhat_beta', ...
    'FADO_omega_e_fast', 'FADO_omega_e_slow', 'FADO_kdf_mode', ...
    'FADO_kaf_mode', 'FADO_flux_limited', 'FADO_Id_Assist_Active'};
for n = 1:numel(required)
    assert(any(strcmp(out.logsout.getElementNames, required{n})), ...
        'Missing required log: %s', required{n});
end

pos_est = localTimeseries(out, 'Pos_PU_est');
speed_est = localTimeseries(out, 'speed_PU_est');
pos_true = localTimeseries(out, 'Pos_PU_true');

position_error = mod(double(pos_est.Data) - interp1(pos_true.Time, double(pos_true.Data), pos_est.Time, 'linear', 'extrap') + 0.5, 1) - 0.5;
true_theta = unwrap(2*pi*double(pos_true.Data));
true_speed_pu = gradient(true_theta, pos_true.Time)/(2*pi*fado.PolePairs) * (60/fado.NBase);
speed_error = double(speed_est.Data) - interp1(pos_true.Time, true_speed_pu, speed_est.Time, 'linear', 'extrap');

fado_logs = {'FADO_lambda_alpha1', 'FADO_lambda_beta1', 'FADO_lambda_alpha2', ...
    'FADO_lambda_beta2', 'FADO_Dhat_alpha', 'FADO_Dhat_beta', ...
    'FADO_omega_e_fast', 'FADO_omega_e_slow'};
all_finite = true;
for n = 1:numel(fado_logs)
    values = localTimeseries(out, fado_logs{n});
    all_finite = all_finite && all(isfinite(double(values.Data)), 'all');
end
assert(all_finite, 'FADO produced NaN or Inf in %s.', scenario.Name);

flux_limited = localTimeseries(out, 'FADO_flux_limited');
kdf_mode = localTimeseries(out, 'FADO_kdf_mode');
kaf_mode = localTimeseries(out, 'FADO_kaf_mode');
id_assist = localTimeseries(out, 'FADO_Id_Assist_Active');

result = localEmptyResult();
result.Name = scenario.Name;
result.Selector = scenario.Selector;
result.RsScale = scenario.RsScale;
result.LqScale = scenario.LqScale;
result.AllFinite = all_finite;
result.PositionRmsePU = sqrt(mean(position_error.^2));
result.PositionPeakPU = max(abs(position_error));
result.SpeedRmsePU = sqrt(mean(speed_error.^2));
result.SpeedPeakPU = max(abs(speed_error));
result.FluxLimitedSamples = nnz(flux_limited.Data);
result.KdfSamples = nnz(kdf_mode.Data);
result.KafSamples = nnz(kaf_mode.Data);
result.IdAssistSamples = nnz(id_assist.Data);
result.StopTime = out.SimulationMetadata.ModelInfo.StopTime;
end

function values = localTimeseries(out, name)
values = out.logsout.get(name).Values;
end

function result = localEmptyResult()
result = struct( ...
    'Name', '', ...
    'Selector', 0, ...
    'RsScale', 1, ...
    'LqScale', 1, ...
    'AllFinite', false, ...
    'PositionRmsePU', NaN, ...
    'PositionPeakPU', NaN, ...
    'SpeedRmsePU', NaN, ...
    'SpeedPeakPU', NaN, ...
    'FluxLimitedSamples', 0, ...
    'KdfSamples', 0, ...
    'KafSamples', 0, ...
    'IdAssistSamples', 0, ...
    'StopTime', '');
end

function localPrintReport(report)
fprintf('\nFADO regression summary\n');
for k = 1:numel(report)
    fprintf(['  %-24s finite=%d posRMSE=%8.5f pu speedRMSE=%8.5f pu ' ...
        'limit=%d kdf=%d kaf=%d idAssist=%d\n'], ...
        report(k).Name, report(k).AllFinite, report(k).PositionRmsePU, ...
        report(k).SpeedRmsePU, report(k).FluxLimitedSamples, ...
        report(k).KdfSamples, report(k).KafSamples, report(k).IdAssistSamples);
end
end
