% Verify the corrected FADO observer gain ordering with ideal rotating flux.
% This is a FADO-only discrete test, not a plant or speed-loop scenario.

mcb_pmsm_foc_sensorless_f28379d_datascript;
mcb_pmsm_foc_sensorless_f28379d_pi_recovery;
mcb_pmsm_foc_sensorless_f28379d_fado_init;

fadoCfg = single([ ...
    fado_Rs fado_RsEstScale fado_Lq fado_LqEstScale fado_PolePairs ...
    fado_Ts fado_VBase fado_IBase fado_NBase fado_FluxLimit ...
    fado_Kdf fado_LowSpeedHz fado_Kaf fado_T2SFastBandwidthHz ...
    fado_T2SSlowBandwidthHz fado_Zeta fado_EnableVoltagePreprocess ...
    fado_VAlphaPreprocess fado_VBetaPreprocess]);

testFrequencyHz = 20;
for direction = [-1, 1]
    omegaElectrical = direction*2*pi*testFrequencyHz;
    equationsFromVector = fado_discrete_equations_v2(fadoCfg, omegaElectrical);
    equationsFromStruct = fado_discrete_equations_v2(fado, omegaElectrical);
    expectedLm = [2*abs(omegaElectrical), -omegaElectrical; ...
                  omegaElectrical, 2*abs(omegaElectrical); ...
                  0, -omegaElectrical; ...
                  omegaElectrical, 0];
    if norm(equationsFromVector.Observer.Lm - expectedLm, 'fro') > 1e-12
        error('FADO:ObserverGainOrder', ...
            'Equation (10-b) gain ordering is incorrect for direction %d.', direction);
    end
    if norm(equationsFromStruct.Observer.Lm - equationsFromVector.Observer.Lm, 'fro') > 1e-12
        error('FADO:ConfigInterface', ...
            'Struct and 19-element vector configurations disagree.');
    end

    result = localRunDirection(direction, testFrequencyHz, fado, fadoCfg);
    if abs(result.thetaErrorRad) > 0.05
        error('FADO:AngleTracking', ...
            'Angle error %.6f rad exceeds the FADO-only test limit.', result.thetaErrorRad);
    end
    if abs(result.speedPu - result.speedTruthPu) > 0.005
        error('FADO:SpeedTracking', ...
            'Speed error %.6f pu exceeds the FADO-only test limit.', ...
            result.speedPu - result.speedTruthPu);
    end
    fprintf(['FADO %+.0f Hz: theta error=%+.6f rad, speed=%+.6f pu, ' ...
        'truth=%+.6f pu.\n'], direction*testFrequencyHz, result.thetaErrorRad, ...
        result.speedPu, result.speedTruthPu);
end

fprintf('FADO observer polarity test passed for positive and negative electrical rotation.\n');

function result = localRunDirection(direction, frequencyHz, fado, fadoCfg)
omegaElectrical = direction*2*pi*frequencyHz;
stepCount = round(2/fado.Ts);

% Reset the persistent reference implementation before each direction.
[~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~] = ...
    fado_estimator_step_v2(zeros(4, 1, 'single'), false, fadoCfg);

for step = 1:stepCount
    time = (step - 1)*fado.Ts;
    angle = omegaElectrical*time;
    viFeedback = single([ ...
        -omegaElectrical*fado.FluxPM*sin(angle)/fado.VBase; ...
         omegaElectrical*fado.FluxPM*cos(angle)/fado.VBase; ...
         0; ...
         0]);
    [posPu, speedPu, lambdaAlpha1, lambdaBeta1, lambdaAlpha2, lambdaBeta2, ...
        dhatAlpha, dhatBeta, omegaFast, omegaSlow, kdfMode, kafMode, fluxLimited] = ...
        fado_estimator_step_v2(viFeedback, true, fadoCfg);

    stateValues = [posPu, speedPu, lambdaAlpha1, lambdaBeta1, lambdaAlpha2, ...
        lambdaBeta2, dhatAlpha, dhatBeta, omegaFast, omegaSlow, ...
        double(kdfMode), double(kafMode), double(fluxLimited)];
    if any(~isfinite(double(stateValues)))
        error('FADO:NonFiniteState', ...
            'FADO state became nonfinite at step %d.', step);
    end
end

truthAngle = omegaElectrical*stepCount*fado.Ts;
estimatedAngle = 2*pi*double(posPu);
result.thetaErrorRad = atan2(sin(estimatedAngle - truthAngle), ...
    cos(estimatedAngle - truthAngle));
result.speedPu = double(speedPu);
result.speedTruthPu = omegaElectrical/(2*pi*fado.PolePairs)*(60/fado.NBase);
end
