function value = vafid_validation_model_data(section)
%VAFID_VALIDATION_MODEL_DATA Deterministic data for closed-loop VAFID MIL.
%   VALUE = VAFID_VALIDATION_MODEL_DATA(SECTION) returns the requested
%   configuration structure or packed VAFID configuration vector. The plant
%   parameters deliberately differ from the identifier nominal values so a
%   passing test proves convergence rather than nominal-value pass-through.

sampleTime_s = 50e-6;

plant = struct( ...
    'sampleTime_s', sampleTime_s, ...
    'rs_Ohm', 0.60, ...
    'ld_H', 1.105e-3, ...
    'lq_H', 1.587e-3, ...
    'fluxPM_Wb', 50.6e-3, ...
    'polePairs', 4.0, ...
    'inertia_kgm2', 2.0e-3, ...
    'viscousFriction_Nm_per_radps', 1.0e-4);

vafidConfig = vafid_default_config();
vafidConfig.requiredAcceptedWindows = uint16(10);
currentBandwidth_radps = 2.0 * pi * 800.0;

controller = struct( ...
    'sampleTime_s', sampleTime_s, ...
    'speedLoopDivider', 10.0, ...
    'currentBase_A', 50.0, ...
    'idBase_A', -2.0, ...
    'iqMinimum_A', -40.0, ...
    'iqMaximum_A', 40.0, ...
    'maximumVoltage_V', 500.0, ...
    'speedSlewRate_rpmps', 2500.0, ...
    'speedKp_A_per_rpm', 0.12, ...
    'speedKi_A_per_rpm_s', 10.5, ...
    'currentKpD_V_per_A', double(vafidConfig.nominalLd_H) * currentBandwidth_radps, ...
    'currentKpQ_V_per_A', double(vafidConfig.nominalLq_H) * currentBandwidth_radps, ...
    'currentKi_V_per_A_s', double(vafidConfig.nominalRs_Ohm) * currentBandwidth_radps, ...
    'currentAntiWindup_per_s', 400.0, ...
    'nominalLd_H', double(vafidConfig.nominalLd_H), ...
    'nominalLq_H', double(vafidConfig.nominalLq_H), ...
    'nominalFluxPM_Wb', double(vafidConfig.nominalFluxPM_Wb));

criteria = struct( ...
    'rsErrorLimit_pct', 5.0, ...
    'ldErrorLimit_pct', 5.0, ...
    'lqErrorLimit_pct', 5.0, ...
    'fluxErrorLimit_pct', 5.0, ...
    'speedRmsErrorLimit_pct', 1.0, ...
    'speedRecoveryBand_pct', 2.0, ...
    'speedRecoveryHold_s', 0.10, ...
    'speedRecoveryLimit_s', 0.75, ...
    'currentRmsErrorLimit_A', 0.50, ...
    'voltageUtilizationLimit_PU', 0.98, ...
    'validFractionMinimum', 0.99, ...
    'relativeResidualLimit', 0.15, ...
    'conditionNumberLimit', 1000.0, ...
    'probeAmplitudeRatioMinimum', 0.80, ...
    'probeAmplitudeRatioMaximum', 1.20, ...
    'probePhaseErrorLimit_deg', 30.0, ...
    'finalAssessmentWindow_s', 0.50, ...
    'postEventGuard_s', 1.50);

switch lower(char(section))
    case 'plant'
        value = plant;
    case 'controller'
        value = controller;
    case 'vafidconfig'
        value = vafidConfig;
    case 'vafidconfigvalues'
        value = vafid_pack_wrapper_config(vafidConfig);
    case 'criteria'
        value = criteria;
    otherwise
        error('VAFID:Validation:UnknownDataSection', ...
            'Unknown validation data section "%s".', char(section));
end
end
