classdef rrcDobFixedPointStepTest < matlab.unittest.TestCase
    %RRCDOBFIXEDPOINTSTEPTEST Integer RRC-DOB reference verification.

    properties (TestParameter)
        operatingPoint = struct( ...
            'rpm800', struct('mechanicalSpeedRpm', 800), ...
            'rpm4000', struct('mechanicalSpeedRpm', 4000))
    end

    methods (Test)
        function testConstantSpeedErrorBudget(testCase, operatingPoint)
            metrics = rrcDobFixedPointStepTest.runReplay( ...
                'constant', operatingPoint.mechanicalSpeedRpm);

            testCase.verifyLessThanOrEqual(metrics.RmsError_LSB, 2, ...
                sprintf('RMS error was %.6f Q15 LSB.', metrics.RmsError_LSB));
            testCase.verifyLessThanOrEqual(metrics.PeakError_LSB, 8, ...
                sprintf('Peak error was %.6f Q15 LSB.', metrics.PeakError_LSB));
            testCase.verifyTrue(metrics.AllStatusesValid);
            testCase.verifyEqual(metrics.ComparedSampleCount, 799);
        end

        function testSweepWithStateRescalingErrorBudget(testCase)
            metrics = rrcDobFixedPointStepTest.runReplay('sweep', 0);

            testCase.verifyLessThanOrEqual(metrics.RmsError_LSB, 2, ...
                sprintf('RMS error was %.6f Q15 LSB.', metrics.RmsError_LSB));
            testCase.verifyLessThanOrEqual(metrics.PeakError_LSB, 8, ...
                sprintf('Peak error was %.6f Q15 LSB.', metrics.PeakError_LSB));
            testCase.verifyTrue(metrics.AllStatusesValid);
            testCase.verifyEqual(metrics.ComparedSampleCount, 799);
        end

        function testExplicitFrequencyStateRescaling(testCase)
            [coefficients, qOld] = ...
                rrcDobFixedPointStepTest.identityCoefficients(single(0.10));
            [~, qNew] = ...
                rrcDobFixedPointStepTest.identityCoefficients(single(0.15));
            state = zeros(8, 1, 'int32');
            state(1:6) = rrcDobFixedPointStepTest.toQ26( ...
                [0.10; 0.20; -0.30; -0.10; -0.20; 0.30]);
            state(7:8) = [qOld; int32(1)];
            expected = rrcDobFixedPointStepTest.toQ26( ...
                [0.10; 0.45; -0.45; -0.10; -0.45; 0.45]);

            [command, estimate, stateNext, status] = rrcDobFixedPointStep( ...
                state, zeros(2, 1, 'int16'), zeros(2, 1, 'int16'), ...
                zeros(2, 1, 'int16'), coefficients, qNew, uint8(0), ...
                uint32(0), int16(32767));

            testCase.verifyEqual(stateNext(1:6), expected, ...
                'AbsTol', int32(2));
            testCase.verifyEqual(stateNext(7:8), [qNew; int32(1)], ...
                'AbsTol', int32(0));
            testCase.verifyEqual(command, zeros(2, 1, 'int16'), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(estimate, zeros(2, 1, 'int16'), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(status, uint8(0));
        end

        function testFirstActivationClearsUnavailableState(testCase)
            [coefficients, qCurrent] = ...
                rrcDobFixedPointStepTest.identityCoefficients(single(0.10));
            state = int32((1:8).');
            state(8) = int32(0);
            rawPi = int16([1000; -1000]);

            [command, estimate, stateNext, status] = rrcDobFixedPointStep( ...
                state, zeros(2, 1, 'int16'), zeros(2, 1, 'int16'), ...
                rawPi, coefficients, qCurrent, uint8(0), uint32(0), ...
                int16(32767));

            testCase.verifyEqual(command, rawPi, 'AbsTol', int16(0));
            testCase.verifyEqual(estimate, zeros(2, 1, 'int16'), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(stateNext(1:6), zeros(6, 1, 'int32'), ...
                'AbsTol', int32(0));
            testCase.verifyEqual(stateNext(7:8), [qCurrent; int32(1)], ...
                'AbsTol', int32(0));
            testCase.verifyEqual(status, uint8(7));
        end

        function testOutOfRangeFrequencyRatioClearsState(testCase)
            [coefficients, qOld] = ...
                rrcDobFixedPointStepTest.identityCoefficients(single(0.10));
            [~, qNew] = ...
                rrcDobFixedPointStepTest.identityCoefficients(single(0.25));
            state = int32((1:8).');
            state(7:8) = [qOld; int32(1)];

            [command, estimate, stateNext, status] = rrcDobFixedPointStep( ...
                state, zeros(2, 1, 'int16'), zeros(2, 1, 'int16'), ...
                int16([100; -100]), coefficients, qNew, uint8(0), ...
                uint32(0), int16(32767));

            testCase.verifyEqual(command, int16([100; -100]), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(estimate, zeros(2, 1, 'int16'), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(stateNext(1:6), zeros(6, 1, 'int32'), ...
                'AbsTol', int32(0));
            testCase.verifyEqual(stateNext(7:8), [qNew; int32(1)], ...
                'AbsTol', int32(0));
            testCase.verifyEqual(status, uint8(7));
        end

        function testExplicitResetClearsFrequencyMemory(testCase)
            [coefficients, qCurrent] = ...
                rrcDobFixedPointStepTest.identityCoefficients(single(0.10));
            state = int32((1:8).');
            rawPi = int16([1200; -900]);

            [command, estimate, stateNext, status] = rrcDobFixedPointStep( ...
                state, zeros(2, 1, 'int16'), zeros(2, 1, 'int16'), ...
                rawPi, coefficients, qCurrent, uint8(1), uint32(0), ...
                int16(32767));

            testCase.verifyEqual(command, rawPi, 'AbsTol', int16(0));
            testCase.verifyEqual(estimate, zeros(2, 1, 'int16'), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(stateNext, zeros(8, 1, 'int32'), ...
                'AbsTol', int32(0));
            testCase.verifyEqual(status, uint8(1));
        end

        function testMacOverflowInvalidatesAndClears(testCase)
            coefficients = repmat(intmax('int32'), 19, 2);
            qCurrent = int32(round(0.1 * 2^29));
            state = repmat(intmax('int32'), 8, 1);
            state(7:8) = [qCurrent; int32(1)];
            rawPi = int16([1000; -1000]);

            [command, estimate, stateNext, status] = rrcDobFixedPointStep( ...
                state, int16([32767; 32767]), int16([32767; 32767]), ...
                rawPi, coefficients, qCurrent, uint8(0), uint32(0), ...
                int16(32767));

            testCase.verifyEqual(command, rawPi, 'AbsTol', int16(0));
            testCase.verifyEqual(estimate, zeros(2, 1, 'int16'), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(stateNext, zeros(8, 1, 'int32'), ...
                'AbsTol', int32(0));
            testCase.verifyEqual(status, uint8(5));
        end

        function testCompensationLimitIsReported(testCase)
            [coefficients, qCurrent] = ...
                rrcDobFixedPointStepTest.identityCoefficients(single(0.10));
            coefficients(16, :) = int32(2^27);
            state = zeros(8, 1, 'int32');
            state(1:6) = rrcDobFixedPointStepTest.toQ26( ...
                [0.5; 0; 0; -0.5; 0; 0]);
            state(7:8) = [qCurrent; int32(1)];
            outputLimit = int16(round(0.1 * 2^15));

            [command, estimate, stateNext, status] = rrcDobFixedPointStep( ...
                state, zeros(2, 1, 'int16'), zeros(2, 1, 'int16'), ...
                int16([10000; -10000]), coefficients, qCurrent, ...
                uint8(0), uint32(2^31), outputLimit);

            testCase.verifyEqual(estimate, int16([16384; -16384]), ...
                'AbsTol', int16(0));
            testCase.verifyEqual(abs(int32(command) - int32([10000; -10000])), ...
                int32([outputLimit; outputLimit]), 'AbsTol', int32(0));
            testCase.verifyEqual(stateNext(1:6), state(1:6), ...
                'AbsTol', int32(0));
            testCase.verifyEqual(status, uint8(6));
        end

        function testApsfsmTenToOneStepErrorBudget(testCase)
            metrics = rrcDobFixedPointStepTest.runReplay('apsfsm', 0);

            testCase.verifyLessThanOrEqual(metrics.RmsError_LSB, 2, ...
                sprintf('RMS error was %.6f Q15 LSB.', metrics.RmsError_LSB));
            testCase.verifyLessThanOrEqual(metrics.PeakError_LSB, 8, ...
                sprintf('Peak error was %.6f Q15 LSB.', metrics.PeakError_LSB));
            testCase.verifyTrue(metrics.AllStatusesValid);
            testCase.verifyEqual(metrics.ComparedSampleCount, 799);
        end
    end

    methods (Static)
        function summary = benchmarkSummary()
            rpm800 = rrcDobFixedPointStepTest.runReplay('constant', 800);
            rpm4000 = rrcDobFixedPointStepTest.runReplay('constant', 4000);
            sweep = rrcDobFixedPointStepTest.runReplay('sweep', 0);
            apsfsm = rrcDobFixedPointStepTest.runReplay('apsfsm', 0);
            caseName = ["800 rpm"; "4000 rpm"; "frequency sweep"; ...
                "APSFSM 10:1 steps"];
            rmsErrorQ15_LSB = [rpm800.RmsError_LSB; rpm4000.RmsError_LSB; ...
                sweep.RmsError_LSB; apsfsm.RmsError_LSB];
            peakErrorQ15_LSB = [rpm800.PeakError_LSB; ...
                rpm4000.PeakError_LSB; sweep.PeakError_LSB; ...
                apsfsm.PeakError_LSB];
            allStatusesValid = [rpm800.AllStatusesValid; ...
                rpm4000.AllStatusesValid; sweep.AllStatusesValid; ...
                apsfsm.AllStatusesValid];
            comparedSampleCount = [rpm800.ComparedSampleCount; ...
                rpm4000.ComparedSampleCount; sweep.ComparedSampleCount; ...
                apsfsm.ComparedSampleCount];
            summary = table(caseName, rmsErrorQ15_LSB, peakErrorQ15_LSB, ...
                allStatusesValid, comparedSampleCount);
        end
    end

    methods (Static, Access = private)
        function metrics = runReplay(replayKind, mechanicalSpeedRpm)
            sampleCount = 800;
            parameters = single([0.5; 1.30e-3; 1.38e-3; 1000; 50; ...
                50e-6; 100; 0.10]);
            ramp_Q31 = uint32(2^31);
            outputLimit_Q15 = int16(round(0.1 * 2^15));
            floatControl = single([0; double(ramp_Q31) / 2^31; ...
                double(outputLimit_Q15) / 2^15]);
            fixedState = zeros(8, 1, 'int32');
            floatState = zeros(8, 1, 'single');
            error_LSB = zeros(2, sampleCount);
            comparedSample = false(1, sampleCount);
            allStatusesValid = true;
            fixedFrequencyResetCount = 0;
            floatFrequencyResetCount = 0;
            phase = 0;
            currentQ = 0;

            for sampleIndex = 1:sampleCount
                [electricalFrequency_Hz, iqReference] = ...
                    rrcDobFixedPointStepTest.replayOperatingPoint( ...
                    replayKind, mechanicalSpeedRpm, sampleIndex, sampleCount);
                parameters(7) = single(electricalFrequency_Hz);
                [coefficients_Q27, q_Q29] = ...
                    rrcDobFixedPointStepTest.quantizedCoefficients(parameters);

                phase = phase + 2 * pi * 6 * electricalFrequency_Hz * ...
                    double(parameters(6));
                if strcmp(replayKind, 'apsfsm')
                    currentQ = currentQ + 0.15 * (iqReference - currentQ);
                    currentPU = [0.01 * sin(phase); currentQ];
                    rawPiPU = [0.02; 0.6 * (iqReference - currentQ)];
                else
                    currentPU = [0.12 * sin(phase); ...
                        0.16 * cos(phase + 0.2)];
                    rawPiPU = [0.18 * sin(phase + 0.3); ...
                        0.22 * cos(phase - 0.1)];
                end
                appliedPU = [0.15 * sin(phase - 0.15); ...
                    0.20 * cos(phase + 0.12)];
                applied_Q15 = rrcDobFixedPointStepTest.toQ15(appliedPU);
                current_Q15 = rrcDobFixedPointStepTest.toQ15(currentPU);
                rawPi_Q15 = rrcDobFixedPointStepTest.toQ15(rawPiPU);
                appliedSingle = single(double(applied_Q15) / 2^15);
                currentSingle = single(double(current_Q15) / 2^15);
                rawPiSingle = single(double(rawPi_Q15) / 2^15);

                [floatCommand, floatEstimate, floatState, floatStatus] = ...
                    rrcDobDiscreteReferenceStep(floatState, appliedSingle, ...
                    currentSingle, rawPiSingle, parameters, floatControl);
                [fixedCommand, fixedEstimate, fixedState, fixedStatus] = ...
                    rrcDobFixedPointStep(fixedState, applied_Q15, ...
                    current_Q15, rawPi_Q15, coefficients_Q27, q_Q29, ...
                    uint8(0), ramp_Q31, outputLimit_Q15);
                expectedCommand_Q15 = ...
                    rrcDobFixedPointStepTest.toQ15(double(floatCommand));
                fixedOperational = fixedStatus == uint8(0) || ...
                    fixedStatus == uint8(6);
                floatOperational = floatStatus == single(0) || ...
                    floatStatus == single(6);
                bothOperational = fixedOperational && floatOperational;
                bothFrequencyReset = fixedStatus == uint8(7) && ...
                    floatStatus == single(7);
                resetOutputsMatch = all(fixedCommand == expectedCommand_Q15) && ...
                    all(fixedEstimate == int16(0)) && ...
                    all(floatEstimate == single(0));
                allStatusesValid = allStatusesValid && ...
                    (bothOperational || (bothFrequencyReset && resetOutputsMatch));
                fixedFrequencyResetCount = fixedFrequencyResetCount + ...
                    double(fixedStatus == uint8(7));
                floatFrequencyResetCount = floatFrequencyResetCount + ...
                    double(floatStatus == single(7));
                if bothOperational
                    error_LSB(:, sampleIndex) = double(fixedCommand) - ...
                        double(expectedCommand_Q15);
                    comparedSample(sampleIndex) = true;
                end
            end

            validErrors_LSB = error_LSB(:, comparedSample);
            if isempty(validErrors_LSB)
                metrics.RmsError_LSB = Inf;
                metrics.PeakError_LSB = Inf;
            else
                metrics.RmsError_LSB = sqrt(mean(validErrors_LSB(:).^2));
                metrics.PeakError_LSB = max(abs(validErrors_LSB(:)));
            end
            metrics.AllStatusesValid = allStatusesValid && ...
                fixedFrequencyResetCount == 1 && ...
                floatFrequencyResetCount == 1;
            metrics.ComparedSampleCount = nnz(comparedSample);
        end

        function [electricalFrequency_Hz, iqReference] = ...
                replayOperatingPoint(replayKind, mechanicalSpeedRpm, ...
                sampleIndex, sampleCount)
            iqReference = 0;
            if strcmp(replayKind, 'constant')
                electricalFrequency_Hz = mechanicalSpeedRpm * 4 / 60;
            elseif strcmp(replayKind, 'sweep')
                sweepFraction = (sampleIndex - 1) / (sampleCount - 1);
                electricalFrequency_Hz = (800 + 3200 * sweepFraction) * 4 / 60;
            else
                electricalFrequency_Hz = 100;
                speedTick = floor((sampleIndex - 1) / 10);
                iqReference = 0.04 * mod(speedTick, 4);
            end
        end

        function [coefficients_Q27, q_Q29] = ...
                quantizedCoefficients(parameters)
            resistance_Ohm = double(parameters(1));
            inductances_H = double(parameters(2:3));
            voltageBase_V = double(parameters(4));
            currentBase_A = double(parameters(5));
            sampleTime_s = double(parameters(6));
            electricalFrequency_Hz = double(parameters(7));
            cutoffRatio = double(parameters(8));
            halfSampleTime_s = sampleTime_s / 2;
            exactQ = tan(2 * pi * 6 * electricalFrequency_Hz * ...
                halfSampleTime_s);
            q_Q29 = int32(round(exactQ * 2^29));
            coefficients_Q27 = zeros(19, 2, 'int32');

            for axisIndex = 1:2
                inductance_H = inductances_H(axisIndex);
                qSquared = exactQ * exactQ;
                twoCutoffQ = 2 * cutoffRatio * exactQ;
                r = resistance_Ohm * halfSampleTime_s / inductance_H;
                onePlusR = 1 + r;
                denominator = 1 + twoCutoffQ + qSquared;
                commonDenominator = onePlusR * denominator;
                voltageInputGain = halfSampleTime_s * voltageBase_V / ...
                    (inductance_H * currentBase_A);
                lambda = inductance_H * currentBase_A / ...
                    (voltageBase_V * sampleTime_s);
                rho = resistance_Ohm * currentBase_A / voltageBase_V;
                coefficients = [ ...
                    ((1-r)*(1+qSquared)-twoCutoffQ*onePlusR) / ...
                        commonDenominator; ...
                    -4*cutoffRatio*exactQ/denominator; ...
                    -4*cutoffRatio*(qSquared-r)/commonDenominator; ...
                    -2*qSquared/commonDenominator; ...
                    (1+twoCutoffQ-qSquared)/denominator; ...
                    2*exactQ*(onePlusR+twoCutoffQ)/commonDenominator; ...
                    -2*exactQ/commonDenominator; ...
                    -2*exactQ/denominator; ...
                    (onePlusR*(1-qSquared)+twoCutoffQ*(1-r)) / ...
                        commonDenominator; ...
                    2*voltageInputGain*(1+qSquared)/commonDenominator; ...
                    4*cutoffRatio*exactQ/denominator; ...
                    -2*voltageInputGain*qSquared/commonDenominator; ...
                    2*qSquared/denominator; ...
                    -2*voltageInputGain*exactQ/commonDenominator; ...
                    2*exactQ/denominator; ...
                    -4*cutoffRatio*exactQ*lambda; ...
                    -4*cutoffRatio*exactQ*lambda; ...
                    2*cutoffRatio*rho; ...
                    4*cutoffRatio*exactQ*lambda];
                coefficients_Q27(:, axisIndex) = int32(round( ...
                    coefficients * 2^27));
            end
        end

        function [coefficients, q_Q29] = identityCoefficients(q)
            coefficients = zeros(19, 2, 'int32');
            coefficients([1, 5, 9], :) = int32(2^27);
            q_Q29 = int32(round(double(q) * 2^29));
        end

        function values_Q15 = toQ15(values)
            valuesWide = round(double(values) * 2^15);
            valuesWide = min(max(valuesWide, double(intmin('int16'))), ...
                double(intmax('int16')));
            values_Q15 = int16(valuesWide);
        end

        function values_Q26 = toQ26(values)
            valuesWide = round(double(values) * 2^26);
            valuesWide = min(max(valuesWide, double(intmin('int32'))), ...
                double(intmax('int32')));
            values_Q26 = int32(valuesWide);
        end
    end
end
