function [Ad,Bd,Cd,Dd] = dv_coefficients_TustinPrewarp(dv_test_K,dv_test_tau,dv_test_T,dv_test_wp)
%dv_coefficients_TustinPrewarp
%    [Ad,Bd,Cd,Dd] = dv_coefficients_TustinPrewarp(dv_test_K,DV_TEST_TAU,dv_test_T,DV_TEST_WP)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026-09-10 22:31:26

t2 = dv_test_wp.*dv_test_tau;
t3 = (dv_test_T.*dv_test_wp)./2.0;
t4 = tan(t3);
t5 = t2+t4;
t6 = 1.0./t5;
Ad = t2.*t6.*2.0-1.0;
if nargout > 1
    Bd = dv_test_tau.*2.0-dv_test_tau.*t2.*t6.*2.0;
end
if nargout > 2
    Cd = dv_test_K.*dv_test_wp.*t6;
end
if nargout > 3
    Dd = dv_test_K-dv_test_K.*t2.*t6;
end
end
