function [Ad,Bd,Cd,Dd] = dv_coefficients_BE(dv_test_K,dv_test_tau,dv_test_T,dv_test_wp)
%dv_coefficients_BE
%    [Ad,Bd,Cd,Dd] = dv_coefficients_BE(dv_test_K,DV_TEST_TAU,dv_test_T,DV_TEST_WP)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026-09-10 22:31:21

t2 = dv_test_T+dv_test_tau;
t3 = 1.0./t2;
Ad = dv_test_tau.*t3;
if nargout > 1
    Bd = dv_test_T.*dv_test_tau.*t3;
end
if nargout > 2
    Cd = dv_test_K.*t3;
end
if nargout > 3
    Dd = dv_test_K.*dv_test_T.*t3;
end
end
