function [b,a] = dv_io_coefficients_BE_o1_i1(dv_test_K,dv_test_tau,dv_test_T,dv_test_wp)
%dv_io_coefficients_BE_o1_i1
%    [B,A] = dv_io_coefficients_BE_o1_i1(dv_test_K,DV_TEST_TAU,dv_test_T,DV_TEST_WP)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026-09-10 22:31:22

t2 = dv_test_T+dv_test_tau;
t3 = 1.0./t2;
b = dv_test_K.*dv_test_T.*t3;
if nargout > 1
    a = [1.0,-dv_test_tau.*t3];
end
end
